package com.fitge.api.exception.exceptionCode;

public class ClientError {
    public static final String INVALID_CLIENT_HEIGHT_ERROR = "INVALID_CLIENT_HEIGHT_ERROR";
    public static final String INVALID_CLIENT_WEIGHT_ERROR = "INVALID_CLIENT_WEIGHT_ERROR";
    public static final String INVALID_CLIENT_WEEK_AVAILABLE_DAYS_ERROR = "INVALID_CLIENT_WEEK_AVAILABLE_DAYS_ERROR";
    public static final String INVALID_CLIENT_DAY_AVAILABLE_HOURS_ERROR = "INVALID_CLIENT_DAY_AVAILABLE_HOURS_ERROR";
    public static final String INVALID_CLIENT_DAILY_CALORIC_INTAKE_ERROR = "INVALID_CLIENT_DAILY_CALORIC_INTAKE_ERROR";
    public static final String INVALID_CLIENT_DAILY_WATER_INTAKE_ERROR = "INVALID_CLIENT_DAILY_WATER_INTAKE_ERROR";
    public static final String INVALID_CLIENT_DAILY_SLEEP_HOURS_ERROR = "INVALID_CLIENT_DAILY_SLEEP_HOURS_ERROR";
    public static final String INVALID_CLIENT_CARDIAC_CONDITIONS_ERROR = "INVALID_CLIENT_CARDIAC_CONDITIONS_ERROR";
    public static final String INVALID_CLIENT_MENTAL_CONDITIONS_ERROR = "INVALID_CLIENT_MENTAL_CONDITIONS_ERROR";
    public static final String INVALID_CLIENT_PHYSICAL_LIMITATIONS_ERROR = "INVALID_CLIENT_PHYSICAL_LIMITATIONS_ERROR";
    public static final String CLIENT_EMPTY_USER_ERROR = "CLIENT_EMPTY_USER_ERROR";
    public static final String CLIENT_NOT_FOUND_ERROR = "CLIENT_NOT_FOUND_ERROR";
}
