package com.fitge.api.exception.exceptionCode;

public class ClientError {
    public static final String INVALID_CLIENT_HEIGHT = "INVALID_CLIENT_HEIGHT";
    public static final String INVALID_CLIENT_WEIGHT = "INVALID_CLIENT_WEIGHT";
    public static final String INVALID_CLIENT_WEEK_AVAILABLE_DAYS = "INVALID_CLIENT_WEEK_AVAILABLE_DAYS";
    public static final String INVALID_CLIENT_DAY_AVAILABLE_HOURS = "INVALID_CLIENT_DAY_AVAILABLE_HOURS";
    public static final String INVALID_CLIENT_DAILY_CALORIC_INTAKE = "INVALID_CLIENT_DAILY_CALORIC_INTAKE";
    public static final String INVALID_CLIENT_DAILY_WATER_INTAKE = "INVALID_CLIENT_DAILY_WATER_INTAKE";
    public static final String INVALID_CLIENT_DAILY_SLEEP_HOURS = "INVALID_CLIENT_DAILY_SLEEP_HOURS";
    public static final String INVALID_CLIENT_CARDIAC_CONDITIONS = "INVALID_CLIENT_CARDIAC_CONDITIONS";
    public static final String INVALID_CLIENT_MENTAL_CONDITIONS = "INVALID_CLIENT_MENTAL_CONDITIONS";
    public static final String INVALID_CLIENT_PHYSICAL_LIMITATIONS = "INVALID_CLIENT_PHYSICAL_LIMITATIONS";
    public static final String CLIENT_EMPTY_USER = "CLIENT_EMPTY_USER";
    public static final String CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND";
}
