package com.fitge.api.exception.exceptionCode;

public class TrainerError {
    public static final String INVALID_TRAINER_DESCRIPTION_ERROR = "INVALID_TRAINER_DESCRIPTION_ERROR";
    public static final String TRAINER_EMPTY_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION_ERROR = "TRAINER_EMPTY_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION_ERROR";
    public static final String INVALID_TRAINER_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION_ERROR = "INVALID_TRAINER_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION_ERROR";
    public static final String TRAINER_EMPTY_MAX_ACTIVE_CONTRACTS_ERROR = "TRAINER_EMPTY_MAX_ACTIVE_CONTRACTS_ERROR";
    public static final String INVALID_TRAINER_MAX_ACTIVE_CONTRACTS_ERROR = "INVALID_TRAINER_MAX_ACTIVE_CONTRACTS_ERROR";
    public static final String TRAINER_EMPTY_IS_REQUEST_BLOCKED_IN_UNAVAILABILITY_ERROR = "TRAINER_EMPTY_IS_REQUEST_BLOCKED_IN_UNAVAILABILITY_ERROR";
    public static final String TRAINER_EMPTY_EMAIL_CLIENT_CHANGES_NOTIFICATION_PERMISSION_ERROR = "TRAINER_EMPTY_EMAIL_CLIENT_CHANGES_NOTIFICATION_PERMISSION_ERROR";
    public static final String TRAINER_EMPTY_APP_CLIENT_CHANGES_NOTIFICATION_PERMISSION_ERROR = "TRAINER_EMPTY_APP_CLIENT_CHANGES_NOTIFICATION_PERMISSION_ERROR";
    public static final String INVALID_TRAINER_WEBSITE_ERROR = "INVALID_TRAINER_WEBSITE_ERROR";
    public static final String TRAINER_EMPTY_USER_ERROR = "TRAINER_EMPTY_USER_ERROR";
    public static final String TRAINER_NOT_FOUND_ERROR = "TRAINER_NOT_FOUND_ERROR";
}
