package com.fitge.api.exception.exceptionCode;

public class TrainerSocialNetworkError {
    public static final String TRAINER_SOCIAL_NETWORK_EMPTY_NAME_ERROR = "TRAINER_SOCIAL_NETWORK_EMPTY_NAME_ERROR";
    public static final String INVALID_TRAINER_SOCIAL_NETWORK_PROFILE_ERROR = "INVALID_TRAINER_SOCIAL_NETWORK_PROFILE_ERROR";
    public static final String TRAINER_SOCIAL_NETWORK_EMPTY_SOCIAL_NETWORK_ERROR = "TRAINER_SOCIAL_NETWORK_EMPTY_SOCIAL_NETWORK_ERROR";
    
}
