package com.fitge.api.exception.exceptionCode;

public class TrainerError {
    public static final String INVALID_TRAINER_DESCRIPTION = "INVALID_TRAINER_DESCRIPTION";
    public static final String TRAINER_EMPTY_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION = "TRAINER_EMPTY_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION";
    public static final String INVALID_TRAINER_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION = "INVALID_TRAINER_DAYS_FOR_CLIENT_CONTRACT_AFTER_PERMISSION";
    public static final String TRAINER_EMPTY_MAX_ACTIVE_CONTRACTS = "TRAINER_EMPTY_MAX_ACTIVE_CONTRACTS";
    public static final String INVALID_TRAINER_MAX_ACTIVE_CONTRACTS = "INVALID_TRAINER_MAX_ACTIVE_CONTRACTS";
    public static final String TRAINER_EMPTY_IS_REQUEST_BLOCKED_IN_UNAVAILABILITY = "TRAINER_EMPTY_IS_REQUEST_BLOCKED_IN_UNAVAILABILITY";
    public static final String TRAINER_EMPTY_EMAIL_CLIENT_CHANGES_NOTIFICATION_PERMISSION = "TRAINER_EMPTY_EMAIL_CLIENT_CHANGES_NOTIFICATION_PERMISSION";
    public static final String TRAINER_EMPTY_APP_CLIENT_CHANGES_NOTIFICATION_PERMISSION = "TRAINER_EMPTY_APP_CLIENT_CHANGES_NOTIFICATION_PERMISSION";
    public static final String INVALID_TRAINER_WEBSITE = "INVALID_TRAINER_WEBSITE";
    public static final String TRAINER_EMPTY_USER = "TRAINER_EMPTY_USER";
    public static final String TRAINER_NOT_FOUND = "TRAINER_NOT_FOUND";
}
