package com.fitge.api.exception.exceptionCode;

public class UserError {
    public static final String USER_EMPTY_NAME_ERROR = "USER_EMPTY_NAME_ERROR";
    public static final String INVALID_USER_NAME_ERROR = "INVALID_USER_NAME_ERROR";
    public static final String USER_EMPTY_NICKNAME_ERROR = "USER_EMPTY_NICKNAME_ERROR";
    public static final String INVALID_USER_NICKNAME_ERROR = "INVALID_USER_NICKNAME_ERROR";
    public static final String USER_EMPTY_EMAIL_ERROR = "USER_EMPTY_EMAIL_ERROR";
    public static final String INVALID_USER_EMAIL_ERROR = "INVALID_USER_EMAIL_ERROR";
    public static final String USER_EMPTY_PASSWORD_ERROR = "USER_EMPTY_PASSWORD_ERROR";
    public static final String INVALID_USER_PASSWORD_ERROR = "INVALID_USER_PASSWORD_ERROR";
    public static final String USER_EMPTY_IS_DARK_THEME_ERROR = "USER_EMPTY_IS_DARK_THEME_ERROR";
    public static final String USER_EMPTY_IS_COMPLAINTER_ANONYMOUS_ERROR = "USER_EMPTY_IS_COMPLAINTER_ANONYMOUS_ERROR";
    public static final String USER_EMPTY_IS_RATER_ANONYMOUS_ERROR = "USER_EMPTY_IS_RATER_ANONYMOUS_ERROR";
    public static final String USER_EMPTY_EMAIL_MESSAGES_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_EMAIL_MESSAGES_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_EMAIL_NEWS_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_EMAIL_NEWS_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_EMAIL_OTHERS_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_EMAIL_OTHERS_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_APP_MESSAGES_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_APP_MESSAGES_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_APP_NEWS_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_APP_NEWS_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_APP_OTHERS_NOTIFICATION_PERMISSION_ERROR = "USER_EMPTY_APP_OTHERS_NOTIFICATION_PERMISSION_ERROR";
    public static final String USER_EMPTY_BIRTHDATE_ERROR = "USER_EMPTY_BIRTHDATE_ERROR";
    public static final String INVALID_USER_AGE_ERROR = "INVALID_USER_AGE_ERROR";
    public static final String USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR";
    public static final String EMAIL_ALREADY_EXISTS_ERROR = "EMAIL_ALREADY_EXISTS_ERROR";
    public static final String NICKNAME_ALREADY_EXISTS_ERROR = "NICKNAME_ALREADY_EXISTS_ERROR";
    public static final String USER_EMPTY_LANGUAGE_ERROR = "NICKNAME_ALREADY_EXISTS_ERROR";

}
