package com.fitge.api.exception.exceptionCode;

public class UserError {
    public static final String USER_EMPTY_NAME = "USER_EMPTY_NAME";
    public static final String INVALID_USER_NAME = "INVALID_USER_NAME";
    public static final String USER_EMPTY_NICKNAME = "USER_EMPTY_NICKNAME";
    public static final String INVALID_USER_NICKNAME = "INVALID_USER_NICKNAME";
    public static final String USER_EMPTY_EMAIL = "USER_EMPTY_EMAIL";
    public static final String INVALID_USER_EMAIL = "INVALID_USER_EMAIL";
    public static final String USER_EMPTY_PASSWORD = "USER_EMPTY_PASSWORD";
    public static final String INVALID_USER_PASSWORD = "INVALID_USER_PASSWORD";
    public static final String USER_EMPTY_IS_DARK_THEME = "USER_EMPTY_IS_DARK_THEME";
    public static final String USER_EMPTY_IS_COMPLAINTER_ANONYMOUS = "USER_EMPTY_IS_COMPLAINTER_ANONYMOUS";
    public static final String USER_EMPTY_IS_RATER_ANONYMOUS = "USER_EMPTY_IS_RATER_ANONYMOUS";
    public static final String USER_EMPTY_EMAIL_MESSAGES_NOTIFICATION_PERMISSION = "USER_EMPTY_EMAIL_MESSAGES_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_EMAIL_NEWS_NOTIFICATION_PERMISSION = "USER_EMPTY_EMAIL_NEWS_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_EMAIL_OTHERS_NOTIFICATION_PERMISSION = "USER_EMPTY_EMAIL_OTHERS_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_APP_MESSAGES_NOTIFICATION_PERMISSION = "USER_EMPTY_APP_MESSAGES_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_APP_NEWS_NOTIFICATION_PERMISSION = "USER_EMPTY_APP_NEWS_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_APP_OTHERS_NOTIFICATION_PERMISSION = "USER_EMPTY_APP_OTHERS_NOTIFICATION_PERMISSION";
    public static final String USER_EMPTY_BIRTHDATE = "USER_EMPTY_BIRTHDATE";
    public static final String INVALID_USER_AGE = "INVALID_USER_AGE";
    public static final String USER_NOT_FOUND = "USER_NOT_FOUND";
    public static final String EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
    public static final String NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS";
    public static final String USER_EMPTY_LANGUAGE = "NICKNAME_ALREADY_EXISTS";

}
